//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MobileReimbursement.SuccessfactorOdataServiceReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SuccessfactorOdataServiceSoap", Namespace="http://Successfactor.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SFAssetDetails[]))]
    public partial class SuccessfactorOdataService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback UpdateEmployeeDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidFormerUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdatePasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback EmployeeAssetDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEmpResignListOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SuccessfactorOdataService() {
            this.Url = global::MobileReimbursement.Properties.Settings.Default.MobileReimbursement_SuccessfactorOdataServiceReference_SuccessfactorOdataService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event UpdateEmployeeDetailsCompletedEventHandler UpdateEmployeeDetailsCompleted;
        
        /// <remarks/>
        public event ValidUserCompletedEventHandler ValidUserCompleted;
        
        /// <remarks/>
        public event ValidFormerUserCompletedEventHandler ValidFormerUserCompleted;
        
        /// <remarks/>
        public event UpdatePasswordCompletedEventHandler UpdatePasswordCompleted;
        
        /// <remarks/>
        public event UserDetailsCompletedEventHandler UserDetailsCompleted;
        
        /// <remarks/>
        public event EmployeeAssetDetailsCompletedEventHandler EmployeeAssetDetailsCompleted;
        
        /// <remarks/>
        public event GetEmpResignListCompletedEventHandler GetEmpResignListCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Successfactor.org/UpdateEmployeeDetails", RequestNamespace="http://Successfactor.org/", ResponseNamespace="http://Successfactor.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WebResponse UpdateEmployeeDetails(string SFEvent, string EventDate) {
            object[] results = this.Invoke("UpdateEmployeeDetails", new object[] {
                        SFEvent,
                        EventDate});
            return ((WebResponse)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateEmployeeDetailsAsync(string SFEvent, string EventDate) {
            this.UpdateEmployeeDetailsAsync(SFEvent, EventDate, null);
        }
        
        /// <remarks/>
        public void UpdateEmployeeDetailsAsync(string SFEvent, string EventDate, object userState) {
            if ((this.UpdateEmployeeDetailsOperationCompleted == null)) {
                this.UpdateEmployeeDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateEmployeeDetailsOperationCompleted);
            }
            this.InvokeAsync("UpdateEmployeeDetails", new object[] {
                        SFEvent,
                        EventDate}, this.UpdateEmployeeDetailsOperationCompleted, userState);
        }
        
        private void OnUpdateEmployeeDetailsOperationCompleted(object arg) {
            if ((this.UpdateEmployeeDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateEmployeeDetailsCompleted(this, new UpdateEmployeeDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Successfactor.org/ValidUser", RequestNamespace="http://Successfactor.org/", ResponseNamespace="http://Successfactor.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ValidUser(string Employeeid, string Password) {
            object[] results = this.Invoke("ValidUser", new object[] {
                        Employeeid,
                        Password});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ValidUserAsync(string Employeeid, string Password) {
            this.ValidUserAsync(Employeeid, Password, null);
        }
        
        /// <remarks/>
        public void ValidUserAsync(string Employeeid, string Password, object userState) {
            if ((this.ValidUserOperationCompleted == null)) {
                this.ValidUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidUserOperationCompleted);
            }
            this.InvokeAsync("ValidUser", new object[] {
                        Employeeid,
                        Password}, this.ValidUserOperationCompleted, userState);
        }
        
        private void OnValidUserOperationCompleted(object arg) {
            if ((this.ValidUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidUserCompleted(this, new ValidUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Successfactor.org/ValidFormerUser", RequestNamespace="http://Successfactor.org/", ResponseNamespace="http://Successfactor.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ValidFormerUser(string Employeeid, string Password) {
            object[] results = this.Invoke("ValidFormerUser", new object[] {
                        Employeeid,
                        Password});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ValidFormerUserAsync(string Employeeid, string Password) {
            this.ValidFormerUserAsync(Employeeid, Password, null);
        }
        
        /// <remarks/>
        public void ValidFormerUserAsync(string Employeeid, string Password, object userState) {
            if ((this.ValidFormerUserOperationCompleted == null)) {
                this.ValidFormerUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidFormerUserOperationCompleted);
            }
            this.InvokeAsync("ValidFormerUser", new object[] {
                        Employeeid,
                        Password}, this.ValidFormerUserOperationCompleted, userState);
        }
        
        private void OnValidFormerUserOperationCompleted(object arg) {
            if ((this.ValidFormerUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidFormerUserCompleted(this, new ValidFormerUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Successfactor.org/UpdatePassword", RequestNamespace="http://Successfactor.org/", ResponseNamespace="http://Successfactor.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdatePassword(string Employeeid, string OldPassword, string NewPassword) {
            object[] results = this.Invoke("UpdatePassword", new object[] {
                        Employeeid,
                        OldPassword,
                        NewPassword});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdatePasswordAsync(string Employeeid, string OldPassword, string NewPassword) {
            this.UpdatePasswordAsync(Employeeid, OldPassword, NewPassword, null);
        }
        
        /// <remarks/>
        public void UpdatePasswordAsync(string Employeeid, string OldPassword, string NewPassword, object userState) {
            if ((this.UpdatePasswordOperationCompleted == null)) {
                this.UpdatePasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdatePasswordOperationCompleted);
            }
            this.InvokeAsync("UpdatePassword", new object[] {
                        Employeeid,
                        OldPassword,
                        NewPassword}, this.UpdatePasswordOperationCompleted, userState);
        }
        
        private void OnUpdatePasswordOperationCompleted(object arg) {
            if ((this.UpdatePasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdatePasswordCompleted(this, new UpdatePasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Successfactor.org/UserDetails", RequestNamespace="http://Successfactor.org/", ResponseNamespace="http://Successfactor.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SFEmployeeDetails[] UserDetails(string Employeeid) {
            object[] results = this.Invoke("UserDetails", new object[] {
                        Employeeid});
            return ((SFEmployeeDetails[])(results[0]));
        }
        
        /// <remarks/>
        public void UserDetailsAsync(string Employeeid) {
            this.UserDetailsAsync(Employeeid, null);
        }
        
        /// <remarks/>
        public void UserDetailsAsync(string Employeeid, object userState) {
            if ((this.UserDetailsOperationCompleted == null)) {
                this.UserDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserDetailsOperationCompleted);
            }
            this.InvokeAsync("UserDetails", new object[] {
                        Employeeid}, this.UserDetailsOperationCompleted, userState);
        }
        
        private void OnUserDetailsOperationCompleted(object arg) {
            if ((this.UserDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserDetailsCompleted(this, new UserDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Successfactor.org/EmployeeAssetDetails", RequestNamespace="http://Successfactor.org/", ResponseNamespace="http://Successfactor.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SFAssetDetails[] EmployeeAssetDetails(string FromDate, string ToDate) {
            object[] results = this.Invoke("EmployeeAssetDetails", new object[] {
                        FromDate,
                        ToDate});
            return ((SFAssetDetails[])(results[0]));
        }
        
        /// <remarks/>
        public void EmployeeAssetDetailsAsync(string FromDate, string ToDate) {
            this.EmployeeAssetDetailsAsync(FromDate, ToDate, null);
        }
        
        /// <remarks/>
        public void EmployeeAssetDetailsAsync(string FromDate, string ToDate, object userState) {
            if ((this.EmployeeAssetDetailsOperationCompleted == null)) {
                this.EmployeeAssetDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEmployeeAssetDetailsOperationCompleted);
            }
            this.InvokeAsync("EmployeeAssetDetails", new object[] {
                        FromDate,
                        ToDate}, this.EmployeeAssetDetailsOperationCompleted, userState);
        }
        
        private void OnEmployeeAssetDetailsOperationCompleted(object arg) {
            if ((this.EmployeeAssetDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EmployeeAssetDetailsCompleted(this, new EmployeeAssetDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Successfactor.org/GetEmpResignList", RequestNamespace="http://Successfactor.org/", ResponseNamespace="http://Successfactor.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetEmpResignList() {
            object[] results = this.Invoke("GetEmpResignList", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetEmpResignListAsync() {
            this.GetEmpResignListAsync(null);
        }
        
        /// <remarks/>
        public void GetEmpResignListAsync(object userState) {
            if ((this.GetEmpResignListOperationCompleted == null)) {
                this.GetEmpResignListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEmpResignListOperationCompleted);
            }
            this.InvokeAsync("GetEmpResignList", new object[0], this.GetEmpResignListOperationCompleted, userState);
        }
        
        private void OnGetEmpResignListOperationCompleted(object arg) {
            if ((this.GetEmpResignListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEmpResignListCompleted(this, new GetEmpResignListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Successfactor.org/")]
    public partial class WebResponse {
        
        private bool statusField;
        
        private string messageField;
        
        private System.DateTime responceTimeField;
        
        private SFEmployeeDetails[] sFEmployeeDetailsField;
        
        private int noRecoredsField;
        
        /// <remarks/>
        public bool Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ResponceTime {
            get {
                return this.responceTimeField;
            }
            set {
                this.responceTimeField = value;
            }
        }
        
        /// <remarks/>
        public SFEmployeeDetails[] SFEmployeeDetails {
            get {
                return this.sFEmployeeDetailsField;
            }
            set {
                this.sFEmployeeDetailsField = value;
            }
        }
        
        /// <remarks/>
        public int NoRecoreds {
            get {
                return this.noRecoredsField;
            }
            set {
                this.noRecoredsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Successfactor.org/")]
    public partial class SFEmployeeDetails {
        
        private string empnoField;
        
        private string empnameField;
        
        private string firstnameField;
        
        private string middlenameField;
        
        private string lastnameField;
        
        private string genderField;
        
        private System.Nullable<System.DateTime> dobField;
        
        private string emailidField;
        
        private string personalEmailidField;
        
        private string mobileField;
        
        private System.Nullable<System.DateTime> dogjField;
        
        private System.Nullable<System.DateTime> dojField;
        
        private string companycodeField;
        
        private string companyField;
        
        private string jobfamilyField;
        
        private string sbucodeField;
        
        private string sbuField;
        
        private string gradecodeField;
        
        private string gradeField;
        
        private string jobcodeField;
        
        private string jobField;
        
        private string designationcodeField;
        
        private string designationField;
        
        private string zonecodeField;
        
        private string zoneField;
        
        private string regioncodeField;
        
        private string regionField;
        
        private string locationcodeField;
        
        private string locationField;
        
        private string costcenterField;
        
        private string empcategorycodeField;
        
        private string functionalmanagerField;
        
        private string employmentstatusField;
        
        private string maritalstatusField;
        
        private string preaddress1Field;
        
        private string preaddress2Field;
        
        private string preaddress3Field;
        
        private string precityField;
        
        private string precountryField;
        
        private string prestateField;
        
        private string prepincodeField;
        
        private System.Nullable<System.DateTime> exitdateField;
        
        private System.Nullable<System.DateTime> entrydateField;
        
        private System.Nullable<System.DateTime> resignationdateField;
        
        private string jobreasonField;
        
        private string verticalcodeField;
        
        private string verticalField;
        
        private string divisioncodeField;
        
        private string divisionField;
        
        private string departmentcodeField;
        
        private string departmentField;
        
        private string subdepartmentcodeField;
        
        private string subdepartmentField;
        
        private string empcategoryField;
        
        private string adminmanagerField;
        
        private string activeField;
        
        private string positiongradeField;
        
        /// <remarks/>
        public string Empno {
            get {
                return this.empnoField;
            }
            set {
                this.empnoField = value;
            }
        }
        
        /// <remarks/>
        public string Empname {
            get {
                return this.empnameField;
            }
            set {
                this.empnameField = value;
            }
        }
        
        /// <remarks/>
        public string Firstname {
            get {
                return this.firstnameField;
            }
            set {
                this.firstnameField = value;
            }
        }
        
        /// <remarks/>
        public string Middlename {
            get {
                return this.middlenameField;
            }
            set {
                this.middlenameField = value;
            }
        }
        
        /// <remarks/>
        public string Lastname {
            get {
                return this.lastnameField;
            }
            set {
                this.lastnameField = value;
            }
        }
        
        /// <remarks/>
        public string Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Dob {
            get {
                return this.dobField;
            }
            set {
                this.dobField = value;
            }
        }
        
        /// <remarks/>
        public string Emailid {
            get {
                return this.emailidField;
            }
            set {
                this.emailidField = value;
            }
        }
        
        /// <remarks/>
        public string PersonalEmailid {
            get {
                return this.personalEmailidField;
            }
            set {
                this.personalEmailidField = value;
            }
        }
        
        /// <remarks/>
        public string Mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Dogj {
            get {
                return this.dogjField;
            }
            set {
                this.dogjField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Doj {
            get {
                return this.dojField;
            }
            set {
                this.dojField = value;
            }
        }
        
        /// <remarks/>
        public string Companycode {
            get {
                return this.companycodeField;
            }
            set {
                this.companycodeField = value;
            }
        }
        
        /// <remarks/>
        public string Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        public string Jobfamily {
            get {
                return this.jobfamilyField;
            }
            set {
                this.jobfamilyField = value;
            }
        }
        
        /// <remarks/>
        public string Sbucode {
            get {
                return this.sbucodeField;
            }
            set {
                this.sbucodeField = value;
            }
        }
        
        /// <remarks/>
        public string Sbu {
            get {
                return this.sbuField;
            }
            set {
                this.sbuField = value;
            }
        }
        
        /// <remarks/>
        public string Gradecode {
            get {
                return this.gradecodeField;
            }
            set {
                this.gradecodeField = value;
            }
        }
        
        /// <remarks/>
        public string Grade {
            get {
                return this.gradeField;
            }
            set {
                this.gradeField = value;
            }
        }
        
        /// <remarks/>
        public string Jobcode {
            get {
                return this.jobcodeField;
            }
            set {
                this.jobcodeField = value;
            }
        }
        
        /// <remarks/>
        public string Job {
            get {
                return this.jobField;
            }
            set {
                this.jobField = value;
            }
        }
        
        /// <remarks/>
        public string Designationcode {
            get {
                return this.designationcodeField;
            }
            set {
                this.designationcodeField = value;
            }
        }
        
        /// <remarks/>
        public string Designation {
            get {
                return this.designationField;
            }
            set {
                this.designationField = value;
            }
        }
        
        /// <remarks/>
        public string Zonecode {
            get {
                return this.zonecodeField;
            }
            set {
                this.zonecodeField = value;
            }
        }
        
        /// <remarks/>
        public string Zone {
            get {
                return this.zoneField;
            }
            set {
                this.zoneField = value;
            }
        }
        
        /// <remarks/>
        public string Regioncode {
            get {
                return this.regioncodeField;
            }
            set {
                this.regioncodeField = value;
            }
        }
        
        /// <remarks/>
        public string Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        public string Locationcode {
            get {
                return this.locationcodeField;
            }
            set {
                this.locationcodeField = value;
            }
        }
        
        /// <remarks/>
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        public string Costcenter {
            get {
                return this.costcenterField;
            }
            set {
                this.costcenterField = value;
            }
        }
        
        /// <remarks/>
        public string Empcategorycode {
            get {
                return this.empcategorycodeField;
            }
            set {
                this.empcategorycodeField = value;
            }
        }
        
        /// <remarks/>
        public string Functionalmanager {
            get {
                return this.functionalmanagerField;
            }
            set {
                this.functionalmanagerField = value;
            }
        }
        
        /// <remarks/>
        public string Employmentstatus {
            get {
                return this.employmentstatusField;
            }
            set {
                this.employmentstatusField = value;
            }
        }
        
        /// <remarks/>
        public string Maritalstatus {
            get {
                return this.maritalstatusField;
            }
            set {
                this.maritalstatusField = value;
            }
        }
        
        /// <remarks/>
        public string Preaddress1 {
            get {
                return this.preaddress1Field;
            }
            set {
                this.preaddress1Field = value;
            }
        }
        
        /// <remarks/>
        public string Preaddress2 {
            get {
                return this.preaddress2Field;
            }
            set {
                this.preaddress2Field = value;
            }
        }
        
        /// <remarks/>
        public string Preaddress3 {
            get {
                return this.preaddress3Field;
            }
            set {
                this.preaddress3Field = value;
            }
        }
        
        /// <remarks/>
        public string Precity {
            get {
                return this.precityField;
            }
            set {
                this.precityField = value;
            }
        }
        
        /// <remarks/>
        public string Precountry {
            get {
                return this.precountryField;
            }
            set {
                this.precountryField = value;
            }
        }
        
        /// <remarks/>
        public string Prestate {
            get {
                return this.prestateField;
            }
            set {
                this.prestateField = value;
            }
        }
        
        /// <remarks/>
        public string Prepincode {
            get {
                return this.prepincodeField;
            }
            set {
                this.prepincodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Exitdate {
            get {
                return this.exitdateField;
            }
            set {
                this.exitdateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Entrydate {
            get {
                return this.entrydateField;
            }
            set {
                this.entrydateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Resignationdate {
            get {
                return this.resignationdateField;
            }
            set {
                this.resignationdateField = value;
            }
        }
        
        /// <remarks/>
        public string Jobreason {
            get {
                return this.jobreasonField;
            }
            set {
                this.jobreasonField = value;
            }
        }
        
        /// <remarks/>
        public string Verticalcode {
            get {
                return this.verticalcodeField;
            }
            set {
                this.verticalcodeField = value;
            }
        }
        
        /// <remarks/>
        public string Vertical {
            get {
                return this.verticalField;
            }
            set {
                this.verticalField = value;
            }
        }
        
        /// <remarks/>
        public string Divisioncode {
            get {
                return this.divisioncodeField;
            }
            set {
                this.divisioncodeField = value;
            }
        }
        
        /// <remarks/>
        public string Division {
            get {
                return this.divisionField;
            }
            set {
                this.divisionField = value;
            }
        }
        
        /// <remarks/>
        public string Departmentcode {
            get {
                return this.departmentcodeField;
            }
            set {
                this.departmentcodeField = value;
            }
        }
        
        /// <remarks/>
        public string Department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
            }
        }
        
        /// <remarks/>
        public string Subdepartmentcode {
            get {
                return this.subdepartmentcodeField;
            }
            set {
                this.subdepartmentcodeField = value;
            }
        }
        
        /// <remarks/>
        public string Subdepartment {
            get {
                return this.subdepartmentField;
            }
            set {
                this.subdepartmentField = value;
            }
        }
        
        /// <remarks/>
        public string Empcategory {
            get {
                return this.empcategoryField;
            }
            set {
                this.empcategoryField = value;
            }
        }
        
        /// <remarks/>
        public string Adminmanager {
            get {
                return this.adminmanagerField;
            }
            set {
                this.adminmanagerField = value;
            }
        }
        
        /// <remarks/>
        public string Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        public string Positiongrade {
            get {
                return this.positiongradeField;
            }
            set {
                this.positiongradeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Successfactor.org/")]
    public partial class SFAssetDetails {
        
        private object assetTypeField;
        
        private object assetModelField;
        
        private object assetSerilaNoField;
        
        private object assetAllocatedToField;
        
        private object statusField;
        
        /// <remarks/>
        public object AssetType {
            get {
                return this.assetTypeField;
            }
            set {
                this.assetTypeField = value;
            }
        }
        
        /// <remarks/>
        public object AssetModel {
            get {
                return this.assetModelField;
            }
            set {
                this.assetModelField = value;
            }
        }
        
        /// <remarks/>
        public object AssetSerilaNo {
            get {
                return this.assetSerilaNoField;
            }
            set {
                this.assetSerilaNoField = value;
            }
        }
        
        /// <remarks/>
        public object AssetAllocatedTo {
            get {
                return this.assetAllocatedToField;
            }
            set {
                this.assetAllocatedToField = value;
            }
        }
        
        /// <remarks/>
        public object Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void UpdateEmployeeDetailsCompletedEventHandler(object sender, UpdateEmployeeDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateEmployeeDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateEmployeeDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WebResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WebResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ValidUserCompletedEventHandler(object sender, ValidUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ValidFormerUserCompletedEventHandler(object sender, ValidFormerUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidFormerUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidFormerUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void UpdatePasswordCompletedEventHandler(object sender, UpdatePasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdatePasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdatePasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void UserDetailsCompletedEventHandler(object sender, UserDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SFEmployeeDetails[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SFEmployeeDetails[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void EmployeeAssetDetailsCompletedEventHandler(object sender, EmployeeAssetDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EmployeeAssetDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EmployeeAssetDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SFAssetDetails[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SFAssetDetails[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetEmpResignListCompletedEventHandler(object sender, GetEmpResignListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEmpResignListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEmpResignListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591