//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileReimbursement.CPLHelperService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://CPLHelpserService.org/", ConfigurationName="CPLHelperService.CPLHelperServiceSoap")]
    public interface CPLHelperServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CPLHelpserService.org/GetApplicationMenu", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MobileReimbursement.CPLHelperService.Applicationmenu[] GetApplicationMenu(long applicationcode, string empcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CPLHelpserService.org/GetApplicationMenu", ReplyAction="*")]
        System.Threading.Tasks.Task<MobileReimbursement.CPLHelperService.Applicationmenu[]> GetApplicationMenuAsync(long applicationcode, string empcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CPLHelpserService.org/HRISValidUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool HRISValidUser(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CPLHelpserService.org/HRISValidUser", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> HRISValidUserAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CPLHelpserService.org/UserDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MobileReimbursement.CPLHelperService.UserLoginData[] UserDetails(string employeeid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CPLHelpserService.org/UserDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<MobileReimbursement.CPLHelperService.UserLoginData[]> UserDetailsAsync(string employeeid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CPLHelpserService.org/ChangeApplicationUserStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ChangeApplicationUserStatus(long applicationcode, string employeeid, long status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CPLHelpserService.org/ChangeApplicationUserStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ChangeApplicationUserStatusAsync(long applicationcode, string employeeid, long status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CPLHelpserService.org/GetApplicationUserRole", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MobileReimbursement.CPLHelperService.ApplicationUserRole[] GetApplicationUserRole(long applicationcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CPLHelpserService.org/GetApplicationUserRole", ReplyAction="*")]
        System.Threading.Tasks.Task<MobileReimbursement.CPLHelperService.ApplicationUserRole[]> GetApplicationUserRoleAsync(long applicationcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CPLHelpserService.org/GetEmployeeApplicationUserRole", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MobileReimbursement.CPLHelperService.ApplicationUserRole[] GetEmployeeApplicationUserRole(long applicationcode, string employeeid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CPLHelpserService.org/GetEmployeeApplicationUserRole", ReplyAction="*")]
        System.Threading.Tasks.Task<MobileReimbursement.CPLHelperService.ApplicationUserRole[]> GetEmployeeApplicationUserRoleAsync(long applicationcode, string employeeid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CPLHelpserService.org/GetHRISEmployeeList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetHRISEmployeeList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CPLHelpserService.org/GetHRISEmployeeList", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetHRISEmployeeListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CPLHelpserService.org/GetHRISEmployeeDetailList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MobileReimbursement.CPLHelperService.EmployeeDetail[] GetHRISEmployeeDetailList(string employeeid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CPLHelpserService.org/GetHRISEmployeeDetailList", ReplyAction="*")]
        System.Threading.Tasks.Task<MobileReimbursement.CPLHelperService.EmployeeDetail[]> GetHRISEmployeeDetailListAsync(string employeeid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CPLHelpserService.org/OtherValidUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool OtherValidUser(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CPLHelpserService.org/OtherValidUser", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> OtherValidUserAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CPLHelpserService.org/OtherUserDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MobileReimbursement.CPLHelperService.UserLoginData[] OtherUserDetails(string employeeid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CPLHelpserService.org/OtherUserDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<MobileReimbursement.CPLHelperService.UserLoginData[]> OtherUserDetailsAsync(string employeeid);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CPLHelpserService.org/")]
    public partial class Applicationmenu : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long applicationcodeField;
        
        private string applicationnameField;
        
        private long menucodeField;
        
        private string menunameField;
        
        private long parentmenucodeField;
        
        private string urlField;
        
        private long rolecodeField;
        
        private string rolenameField;
        
        private string empcodeField;
        
        private string accesskeyField;
        
        private long divisionField;
        
        private string divnameField;
        
        private long unitField;
        
        private string unitnameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long Applicationcode {
            get {
                return this.applicationcodeField;
            }
            set {
                this.applicationcodeField = value;
                this.RaisePropertyChanged("Applicationcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Applicationname {
            get {
                return this.applicationnameField;
            }
            set {
                this.applicationnameField = value;
                this.RaisePropertyChanged("Applicationname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long Menucode {
            get {
                return this.menucodeField;
            }
            set {
                this.menucodeField = value;
                this.RaisePropertyChanged("Menucode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Menuname {
            get {
                return this.menunameField;
            }
            set {
                this.menunameField = value;
                this.RaisePropertyChanged("Menuname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public long Parentmenucode {
            get {
                return this.parentmenucodeField;
            }
            set {
                this.parentmenucodeField = value;
                this.RaisePropertyChanged("Parentmenucode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("Url");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public long Rolecode {
            get {
                return this.rolecodeField;
            }
            set {
                this.rolecodeField = value;
                this.RaisePropertyChanged("Rolecode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Rolename {
            get {
                return this.rolenameField;
            }
            set {
                this.rolenameField = value;
                this.RaisePropertyChanged("Rolename");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Empcode {
            get {
                return this.empcodeField;
            }
            set {
                this.empcodeField = value;
                this.RaisePropertyChanged("Empcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Accesskey {
            get {
                return this.accesskeyField;
            }
            set {
                this.accesskeyField = value;
                this.RaisePropertyChanged("Accesskey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public long Division {
            get {
                return this.divisionField;
            }
            set {
                this.divisionField = value;
                this.RaisePropertyChanged("Division");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Divname {
            get {
                return this.divnameField;
            }
            set {
                this.divnameField = value;
                this.RaisePropertyChanged("Divname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public long Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
                this.RaisePropertyChanged("Unit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Unitname {
            get {
                return this.unitnameField;
            }
            set {
                this.unitnameField = value;
                this.RaisePropertyChanged("Unitname");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CPLHelpserService.org/")]
    public partial class EmployeeDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string empnoField;
        
        private string empnameField;
        
        private string genderField;
        
        private string companyField;
        
        private string cmpnameField;
        
        private string divisionField;
        
        private string divnameField;
        
        private string unitField;
        
        private string untnameField;
        
        private string deptField;
        
        private string deptnameField;
        
        private string emptypeField;
        
        private string mngtgrpField;
        
        private string desgnameField;
        
        private string joindtField;
        
        private string grpjndtField;
        
        private string cleardtField;
        
        private string resigndtField;
        
        private string confrmdtField;
        
        private string trnsfrdtField;
        
        private string reportingSupervisorField;
        
        private string hodField;
        
        private string shiftField;
        
        private string holidayField;
        
        private string pmtdayField;
        
        private string daidField;
        
        private string vdacodeField;
        
        private string pfcodeField;
        
        private string esicodeField;
        
        private string pannoField;
        
        private string aadharnoField;
        
        private string pmtflgField;
        
        private string bankcodeField;
        
        private string bkaccodeField;
        
        private string bkifsccodeField;
        
        private string maritalsField;
        
        private string marrgdtField;
        
        private string bldgrpField;
        
        private string emailidField;
        
        private string mobileField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Empno {
            get {
                return this.empnoField;
            }
            set {
                this.empnoField = value;
                this.RaisePropertyChanged("Empno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Empname {
            get {
                return this.empnameField;
            }
            set {
                this.empnameField = value;
                this.RaisePropertyChanged("Empname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
                this.RaisePropertyChanged("Gender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
                this.RaisePropertyChanged("Company");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Cmpname {
            get {
                return this.cmpnameField;
            }
            set {
                this.cmpnameField = value;
                this.RaisePropertyChanged("Cmpname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Division {
            get {
                return this.divisionField;
            }
            set {
                this.divisionField = value;
                this.RaisePropertyChanged("Division");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Divname {
            get {
                return this.divnameField;
            }
            set {
                this.divnameField = value;
                this.RaisePropertyChanged("Divname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
                this.RaisePropertyChanged("Unit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Untname {
            get {
                return this.untnameField;
            }
            set {
                this.untnameField = value;
                this.RaisePropertyChanged("Untname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Dept {
            get {
                return this.deptField;
            }
            set {
                this.deptField = value;
                this.RaisePropertyChanged("Dept");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Deptname {
            get {
                return this.deptnameField;
            }
            set {
                this.deptnameField = value;
                this.RaisePropertyChanged("Deptname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Emptype {
            get {
                return this.emptypeField;
            }
            set {
                this.emptypeField = value;
                this.RaisePropertyChanged("Emptype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Mngtgrp {
            get {
                return this.mngtgrpField;
            }
            set {
                this.mngtgrpField = value;
                this.RaisePropertyChanged("Mngtgrp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Desgname {
            get {
                return this.desgnameField;
            }
            set {
                this.desgnameField = value;
                this.RaisePropertyChanged("Desgname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Joindt {
            get {
                return this.joindtField;
            }
            set {
                this.joindtField = value;
                this.RaisePropertyChanged("Joindt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Grpjndt {
            get {
                return this.grpjndtField;
            }
            set {
                this.grpjndtField = value;
                this.RaisePropertyChanged("Grpjndt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Cleardt {
            get {
                return this.cleardtField;
            }
            set {
                this.cleardtField = value;
                this.RaisePropertyChanged("Cleardt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string Resigndt {
            get {
                return this.resigndtField;
            }
            set {
                this.resigndtField = value;
                this.RaisePropertyChanged("Resigndt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Confrmdt {
            get {
                return this.confrmdtField;
            }
            set {
                this.confrmdtField = value;
                this.RaisePropertyChanged("Confrmdt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Trnsfrdt {
            get {
                return this.trnsfrdtField;
            }
            set {
                this.trnsfrdtField = value;
                this.RaisePropertyChanged("Trnsfrdt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string ReportingSupervisor {
            get {
                return this.reportingSupervisorField;
            }
            set {
                this.reportingSupervisorField = value;
                this.RaisePropertyChanged("ReportingSupervisor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string Hod {
            get {
                return this.hodField;
            }
            set {
                this.hodField = value;
                this.RaisePropertyChanged("Hod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string Shift {
            get {
                return this.shiftField;
            }
            set {
                this.shiftField = value;
                this.RaisePropertyChanged("Shift");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string Holiday {
            get {
                return this.holidayField;
            }
            set {
                this.holidayField = value;
                this.RaisePropertyChanged("Holiday");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string Pmtday {
            get {
                return this.pmtdayField;
            }
            set {
                this.pmtdayField = value;
                this.RaisePropertyChanged("Pmtday");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string Daid {
            get {
                return this.daidField;
            }
            set {
                this.daidField = value;
                this.RaisePropertyChanged("Daid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string Vdacode {
            get {
                return this.vdacodeField;
            }
            set {
                this.vdacodeField = value;
                this.RaisePropertyChanged("Vdacode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string Pfcode {
            get {
                return this.pfcodeField;
            }
            set {
                this.pfcodeField = value;
                this.RaisePropertyChanged("Pfcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string Esicode {
            get {
                return this.esicodeField;
            }
            set {
                this.esicodeField = value;
                this.RaisePropertyChanged("Esicode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string Panno {
            get {
                return this.pannoField;
            }
            set {
                this.pannoField = value;
                this.RaisePropertyChanged("Panno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string Aadharno {
            get {
                return this.aadharnoField;
            }
            set {
                this.aadharnoField = value;
                this.RaisePropertyChanged("Aadharno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string Pmtflg {
            get {
                return this.pmtflgField;
            }
            set {
                this.pmtflgField = value;
                this.RaisePropertyChanged("Pmtflg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string Bankcode {
            get {
                return this.bankcodeField;
            }
            set {
                this.bankcodeField = value;
                this.RaisePropertyChanged("Bankcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string Bkaccode {
            get {
                return this.bkaccodeField;
            }
            set {
                this.bkaccodeField = value;
                this.RaisePropertyChanged("Bkaccode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string Bkifsccode {
            get {
                return this.bkifsccodeField;
            }
            set {
                this.bkifsccodeField = value;
                this.RaisePropertyChanged("Bkifsccode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string Maritals {
            get {
                return this.maritalsField;
            }
            set {
                this.maritalsField = value;
                this.RaisePropertyChanged("Maritals");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public string Marrgdt {
            get {
                return this.marrgdtField;
            }
            set {
                this.marrgdtField = value;
                this.RaisePropertyChanged("Marrgdt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public string Bldgrp {
            get {
                return this.bldgrpField;
            }
            set {
                this.bldgrpField = value;
                this.RaisePropertyChanged("Bldgrp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public string Emailid {
            get {
                return this.emailidField;
            }
            set {
                this.emailidField = value;
                this.RaisePropertyChanged("Emailid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public string Mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
                this.RaisePropertyChanged("Mobile");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CPLHelpserService.org/")]
    public partial class ApplicationUserRole : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long rolecodeField;
        
        private string rolenameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long Rolecode {
            get {
                return this.rolecodeField;
            }
            set {
                this.rolecodeField = value;
                this.RaisePropertyChanged("Rolecode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Rolename {
            get {
                return this.rolenameField;
            }
            set {
                this.rolenameField = value;
                this.RaisePropertyChanged("Rolename");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CPLHelpserService.org/")]
    public partial class UserLoginData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eMPNOField;
        
        private string eMPNAMEField;
        
        private int sTATUSField;
        
        private string mailIDField;
        
        private string mobileNoField;
        
        private string usertypeField;
        
        private string emptypeField;
        
        private string divisionField;
        
        private string divisionnameField;
        
        private long unitField;
        
        private string unitnameField;
        
        private long loccdField;
        
        private string locnameField;
        
        private long companyField;
        
        private string cmpnameField;
        
        private int yearField;
        
        private int monthField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EMPNO {
            get {
                return this.eMPNOField;
            }
            set {
                this.eMPNOField = value;
                this.RaisePropertyChanged("EMPNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string EMPNAME {
            get {
                return this.eMPNAMEField;
            }
            set {
                this.eMPNAMEField = value;
                this.RaisePropertyChanged("EMPNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
                this.RaisePropertyChanged("STATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MailID {
            get {
                return this.mailIDField;
            }
            set {
                this.mailIDField = value;
                this.RaisePropertyChanged("MailID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string MobileNo {
            get {
                return this.mobileNoField;
            }
            set {
                this.mobileNoField = value;
                this.RaisePropertyChanged("MobileNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Usertype {
            get {
                return this.usertypeField;
            }
            set {
                this.usertypeField = value;
                this.RaisePropertyChanged("Usertype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Emptype {
            get {
                return this.emptypeField;
            }
            set {
                this.emptypeField = value;
                this.RaisePropertyChanged("Emptype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Division {
            get {
                return this.divisionField;
            }
            set {
                this.divisionField = value;
                this.RaisePropertyChanged("Division");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Divisionname {
            get {
                return this.divisionnameField;
            }
            set {
                this.divisionnameField = value;
                this.RaisePropertyChanged("Divisionname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public long Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
                this.RaisePropertyChanged("Unit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Unitname {
            get {
                return this.unitnameField;
            }
            set {
                this.unitnameField = value;
                this.RaisePropertyChanged("Unitname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public long Loccd {
            get {
                return this.loccdField;
            }
            set {
                this.loccdField = value;
                this.RaisePropertyChanged("Loccd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Locname {
            get {
                return this.locnameField;
            }
            set {
                this.locnameField = value;
                this.RaisePropertyChanged("Locname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public long Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
                this.RaisePropertyChanged("Company");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Cmpname {
            get {
                return this.cmpnameField;
            }
            set {
                this.cmpnameField = value;
                this.RaisePropertyChanged("Cmpname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public int Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
                this.RaisePropertyChanged("Year");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public int Month {
            get {
                return this.monthField;
            }
            set {
                this.monthField = value;
                this.RaisePropertyChanged("Month");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CPLHelperServiceSoapChannel : MobileReimbursement.CPLHelperService.CPLHelperServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CPLHelperServiceSoapClient : System.ServiceModel.ClientBase<MobileReimbursement.CPLHelperService.CPLHelperServiceSoap>, MobileReimbursement.CPLHelperService.CPLHelperServiceSoap {
        
        public CPLHelperServiceSoapClient() {
        }
        
        public CPLHelperServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CPLHelperServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CPLHelperServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CPLHelperServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MobileReimbursement.CPLHelperService.Applicationmenu[] GetApplicationMenu(long applicationcode, string empcode) {
            return base.Channel.GetApplicationMenu(applicationcode, empcode);
        }
        
        public System.Threading.Tasks.Task<MobileReimbursement.CPLHelperService.Applicationmenu[]> GetApplicationMenuAsync(long applicationcode, string empcode) {
            return base.Channel.GetApplicationMenuAsync(applicationcode, empcode);
        }
        
        public bool HRISValidUser(string username, string password) {
            return base.Channel.HRISValidUser(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> HRISValidUserAsync(string username, string password) {
            return base.Channel.HRISValidUserAsync(username, password);
        }
        
        public MobileReimbursement.CPLHelperService.UserLoginData[] UserDetails(string employeeid) {
            return base.Channel.UserDetails(employeeid);
        }
        
        public System.Threading.Tasks.Task<MobileReimbursement.CPLHelperService.UserLoginData[]> UserDetailsAsync(string employeeid) {
            return base.Channel.UserDetailsAsync(employeeid);
        }
        
        public bool ChangeApplicationUserStatus(long applicationcode, string employeeid, long status) {
            return base.Channel.ChangeApplicationUserStatus(applicationcode, employeeid, status);
        }
        
        public System.Threading.Tasks.Task<bool> ChangeApplicationUserStatusAsync(long applicationcode, string employeeid, long status) {
            return base.Channel.ChangeApplicationUserStatusAsync(applicationcode, employeeid, status);
        }
        
        public MobileReimbursement.CPLHelperService.ApplicationUserRole[] GetApplicationUserRole(long applicationcode) {
            return base.Channel.GetApplicationUserRole(applicationcode);
        }
        
        public System.Threading.Tasks.Task<MobileReimbursement.CPLHelperService.ApplicationUserRole[]> GetApplicationUserRoleAsync(long applicationcode) {
            return base.Channel.GetApplicationUserRoleAsync(applicationcode);
        }
        
        public MobileReimbursement.CPLHelperService.ApplicationUserRole[] GetEmployeeApplicationUserRole(long applicationcode, string employeeid) {
            return base.Channel.GetEmployeeApplicationUserRole(applicationcode, employeeid);
        }
        
        public System.Threading.Tasks.Task<MobileReimbursement.CPLHelperService.ApplicationUserRole[]> GetEmployeeApplicationUserRoleAsync(long applicationcode, string employeeid) {
            return base.Channel.GetEmployeeApplicationUserRoleAsync(applicationcode, employeeid);
        }
        
        public System.Data.DataTable GetHRISEmployeeList() {
            return base.Channel.GetHRISEmployeeList();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetHRISEmployeeListAsync() {
            return base.Channel.GetHRISEmployeeListAsync();
        }
        
        public MobileReimbursement.CPLHelperService.EmployeeDetail[] GetHRISEmployeeDetailList(string employeeid) {
            return base.Channel.GetHRISEmployeeDetailList(employeeid);
        }
        
        public System.Threading.Tasks.Task<MobileReimbursement.CPLHelperService.EmployeeDetail[]> GetHRISEmployeeDetailListAsync(string employeeid) {
            return base.Channel.GetHRISEmployeeDetailListAsync(employeeid);
        }
        
        public bool OtherValidUser(string username, string password) {
            return base.Channel.OtherValidUser(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> OtherValidUserAsync(string username, string password) {
            return base.Channel.OtherValidUserAsync(username, password);
        }
        
        public MobileReimbursement.CPLHelperService.UserLoginData[] OtherUserDetails(string employeeid) {
            return base.Channel.OtherUserDetails(employeeid);
        }
        
        public System.Threading.Tasks.Task<MobileReimbursement.CPLHelperService.UserLoginData[]> OtherUserDetailsAsync(string employeeid) {
            return base.Channel.OtherUserDetailsAsync(employeeid);
        }
    }
}
