//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagement.WorkLineServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cplworkline.org/", ConfigurationName="WorkLineServiceReference.WorklineServiceSoap")]
    public interface WorklineServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cplworkline.org/WorklineValidUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool WorklineValidUser(string Empid, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cplworkline.org/WorklineValidUser", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> WorklineValidUserAsync(string Empid, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cplworkline.org/UserDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AssetManagement.WorkLineServiceReference.UserLoginData[] UserDetails(string employeeid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cplworkline.org/UserDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<AssetManagement.WorkLineServiceReference.UserLoginData[]> UserDetailsAsync(string employeeid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cplworkline.org/GetPayslipUrl", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetPayslipUrl(string Empid, int Year, int Month);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cplworkline.org/GetPayslipUrl", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetPayslipUrlAsync(string Empid, int Year, int Month);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cplworkline.org/GetCPLSSOUrl", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetCPLSSOUrl();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cplworkline.org/GetCPLSSOUrl", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetCPLSSOUrlAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cplworkline.org/SetResignInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SetResignInfo(string Empid, System.DateTime Resigndate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cplworkline.org/SetResignInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> SetResignInfoAsync(string Empid, System.DateTime Resigndate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cplworkline.org/EncryptEmployeeID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string EncryptEmployeeID(string Empid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cplworkline.org/EncryptEmployeeID", ReplyAction="*")]
        System.Threading.Tasks.Task<string> EncryptEmployeeIDAsync(string Empid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cplworkline.org/DecryptEmployeeID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DecryptEmployeeID(string EncryptedEmpid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cplworkline.org/DecryptEmployeeID", ReplyAction="*")]
        System.Threading.Tasks.Task<string> DecryptEmployeeIDAsync(string EncryptedEmpid);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cplworkline.org/")]
    public partial class UserLoginData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eMPNOField;
        
        private string eMPNAMEField;
        
        private int sTATUSField;
        
        private string mailIDField;
        
        private string mobileNoField;
        
        private string usertypeField;
        
        private string emptypeField;
        
        private string divisionField;
        
        private string divisionnameField;
        
        private long unitField;
        
        private string unitnameField;
        
        private long loccdField;
        
        private string locnameField;
        
        private long companyField;
        
        private string cmpnameField;
        
        private int yearField;
        
        private int monthField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EMPNO {
            get {
                return this.eMPNOField;
            }
            set {
                this.eMPNOField = value;
                this.RaisePropertyChanged("EMPNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string EMPNAME {
            get {
                return this.eMPNAMEField;
            }
            set {
                this.eMPNAMEField = value;
                this.RaisePropertyChanged("EMPNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
                this.RaisePropertyChanged("STATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MailID {
            get {
                return this.mailIDField;
            }
            set {
                this.mailIDField = value;
                this.RaisePropertyChanged("MailID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string MobileNo {
            get {
                return this.mobileNoField;
            }
            set {
                this.mobileNoField = value;
                this.RaisePropertyChanged("MobileNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Usertype {
            get {
                return this.usertypeField;
            }
            set {
                this.usertypeField = value;
                this.RaisePropertyChanged("Usertype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Emptype {
            get {
                return this.emptypeField;
            }
            set {
                this.emptypeField = value;
                this.RaisePropertyChanged("Emptype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Division {
            get {
                return this.divisionField;
            }
            set {
                this.divisionField = value;
                this.RaisePropertyChanged("Division");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Divisionname {
            get {
                return this.divisionnameField;
            }
            set {
                this.divisionnameField = value;
                this.RaisePropertyChanged("Divisionname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public long Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
                this.RaisePropertyChanged("Unit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Unitname {
            get {
                return this.unitnameField;
            }
            set {
                this.unitnameField = value;
                this.RaisePropertyChanged("Unitname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public long Loccd {
            get {
                return this.loccdField;
            }
            set {
                this.loccdField = value;
                this.RaisePropertyChanged("Loccd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Locname {
            get {
                return this.locnameField;
            }
            set {
                this.locnameField = value;
                this.RaisePropertyChanged("Locname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public long Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
                this.RaisePropertyChanged("Company");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Cmpname {
            get {
                return this.cmpnameField;
            }
            set {
                this.cmpnameField = value;
                this.RaisePropertyChanged("Cmpname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public int Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
                this.RaisePropertyChanged("Year");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public int Month {
            get {
                return this.monthField;
            }
            set {
                this.monthField = value;
                this.RaisePropertyChanged("Month");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WorklineServiceSoapChannel : AssetManagement.WorkLineServiceReference.WorklineServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WorklineServiceSoapClient : System.ServiceModel.ClientBase<AssetManagement.WorkLineServiceReference.WorklineServiceSoap>, AssetManagement.WorkLineServiceReference.WorklineServiceSoap {
        
        public WorklineServiceSoapClient() {
        }
        
        public WorklineServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WorklineServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorklineServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorklineServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool WorklineValidUser(string Empid, string Password) {
            return base.Channel.WorklineValidUser(Empid, Password);
        }
        
        public System.Threading.Tasks.Task<bool> WorklineValidUserAsync(string Empid, string Password) {
            return base.Channel.WorklineValidUserAsync(Empid, Password);
        }
        
        public AssetManagement.WorkLineServiceReference.UserLoginData[] UserDetails(string employeeid) {
            return base.Channel.UserDetails(employeeid);
        }
        
        public System.Threading.Tasks.Task<AssetManagement.WorkLineServiceReference.UserLoginData[]> UserDetailsAsync(string employeeid) {
            return base.Channel.UserDetailsAsync(employeeid);
        }
        
        public string GetPayslipUrl(string Empid, int Year, int Month) {
            return base.Channel.GetPayslipUrl(Empid, Year, Month);
        }
        
        public System.Threading.Tasks.Task<string> GetPayslipUrlAsync(string Empid, int Year, int Month) {
            return base.Channel.GetPayslipUrlAsync(Empid, Year, Month);
        }
        
        public string GetCPLSSOUrl() {
            return base.Channel.GetCPLSSOUrl();
        }
        
        public System.Threading.Tasks.Task<string> GetCPLSSOUrlAsync() {
            return base.Channel.GetCPLSSOUrlAsync();
        }
        
        public bool SetResignInfo(string Empid, System.DateTime Resigndate) {
            return base.Channel.SetResignInfo(Empid, Resigndate);
        }
        
        public System.Threading.Tasks.Task<bool> SetResignInfoAsync(string Empid, System.DateTime Resigndate) {
            return base.Channel.SetResignInfoAsync(Empid, Resigndate);
        }
        
        public string EncryptEmployeeID(string Empid) {
            return base.Channel.EncryptEmployeeID(Empid);
        }
        
        public System.Threading.Tasks.Task<string> EncryptEmployeeIDAsync(string Empid) {
            return base.Channel.EncryptEmployeeIDAsync(Empid);
        }
        
        public string DecryptEmployeeID(string EncryptedEmpid) {
            return base.Channel.DecryptEmployeeID(EncryptedEmpid);
        }
        
        public System.Threading.Tasks.Task<string> DecryptEmployeeIDAsync(string EncryptedEmpid) {
            return base.Channel.DecryptEmployeeIDAsync(EncryptedEmpid);
        }
    }
}
